### ISSUE TITLE
Does not display on Atom 208

### ISSUE THREAD

**Issue by JohnMurga** [forgecrafted/rulerz#10]
Other similar packages have the same issue with 208

**Comment by cmtonkinson** [comment]
Duplicate of #8

**Comment by JohnMurga** [comment]
Not really ...
But I guess the net effect is similar : https://github.com/atom/atom/issues/7204
I raised the issue on Atom also as it affects a few packages on 208 (while 207 is fine)

**Comment by cmtonkinson** [comment]
@JohnMurga looks like you're right, these are distinct-but-related changes that happened in quick succession.

**Comment by cmtonkinson** [comment]
Going to investigate using Markers instead of relying on manipulating layers in the editor directly.

**Comment by JohnMurga** [comment]
I got a response that may be useful ...
https://github.com/atom/atom/issues/7204#event-327883949

**Comment by cmtonkinson** [comment]
Good call, @JohnMurga. Inserting into the shadowRoot gets it closer, but still having issues. First, the ruler gets thrown off horizontally by e.g. having line numbers enabled, and second, when the ruler _is_ positioned correctly, it overlays the cursor so you don't see the blink effect.

Opacity could be a solution to the latter but it's probably not worth thinking too hard about before we figure out if adding a custom element to the shadowRoot is even the right way to move forward. Considered using Markers instead of "manual" DOM manipulation - thoughts anyone?

**Comment by cmtonkinson** [comment]
Another idea entirely is to replace all of the JS code with a pure-CSS solution. The following is a rough draft:

``` less
atom-text-editor.is-focused::shadow {
  .cursors {
    .cursor::before {
      content: " ";
      display: block;
      height: 100%;
      width: 1px;
      transform: translateX(-0px) scaleY(1000);
      border-left: 1px solid @text-color-subtle;
      overflow: hidden;
    }
  }
}
```

Two problems with this approach though:
1. The ruler blinks with the cursor (and since .cursors.blink-off uses `opacity` instead of `rgba`, I don't see a clean way around this)
2. Using `translateX(-1px)` to align the ruler perfectly with the cusor, hides the cursor (even when setting a negative `z-index` to try to force the ruler "behind" the cursor)
